---
- name: Install HAProxy Package
  yum:
    name: haproxy
    state: latest

- name: Set HAProxy Service to Start at Boot
  service:
    name: haproxy
    enabled: yes

- name: Update HAProxy Configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: Start HAProxy
  service:
    name: haproxy
    state: started
 
